### ISSUE TITLE
auth header is missing when use grpcgateway get new tx

### ISSUE THREAD

**Issue by MRqin** [bloXroute-Labs/bloxroute-sdk-go#12]
I try :
package main

import (
	"context"
	sdk "github.com/bloXroute-Labs/bloxroute-sdk-go"
	"log"
)

func main() {
	// create a config
	config := &sdk.Config{
		AuthHeader: "my header",
		// WSGatewayURL: "ws://127.0.0.1:28333/ws",
		GRPCGatewayURL: "grpc://localhost:5001",
	}

	ctx := context.Background()

	// create a new client
	c, err := sdk.NewClient(ctx, config)
	if err != nil {
		log.Fatal(err)
	}

	// subscribe to new transactions
	if err = c.OnNewTx(ctx, &sdk.NewTxParams{Include: []string{"raw_tx", "tx_contents"}}, func(ctx context.Context, err error, result *sdk.NewTxNotification) {
		if err != nil {
			log.Fatal(err)  //**got err here**
		}

		// handle result
		log.Println(result.TxContents.From, result.TxContents.Input)
	}); err != nil {
		log.Fatal(err)
	}

	select {}
}，but  c.OnNewTx retrun the error ： rpc error: code = Unknown desc = auth header is missing,
I set my correct AuthHeader when  sdk config init，why got this err

**Comment by bogdanprodanj** [comment]
Hi! I just tested this with the latest SDK version, and everything works fine. I'm closing this issue for now.
